// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYzHPbON-icFvsd4WpcoeXAQiRAyPh-rc',
    appId: '1:60705047358:web:2f43fa751a686df9b5a26f',
    messagingSenderId: '60705047358',
    projectId: 'pr23-ebf71',
    authDomain: 'pr23-ebf71.firebaseapp.com',
    storageBucket: 'pr23-ebf71.firebasestorage.app',
    measurementId: 'G-VKVZHBX5QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDwMhuR7kL4oL1Mr2ZQ64PZ0nIaWaiM9s',
    appId: '1:60705047358:android:d9b851934c5af2abb5a26f',
    messagingSenderId: '60705047358',
    projectId: 'pr23-ebf71',
    storageBucket: 'pr23-ebf71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3yJT1gC7NyENiZFBbUaa3OaXYTJJO89o',
    appId: '1:60705047358:ios:d43f89bd9e6423f4b5a26f',
    messagingSenderId: '60705047358',
    projectId: 'pr23-ebf71',
    storageBucket: 'pr23-ebf71.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3yJT1gC7NyENiZFBbUaa3OaXYTJJO89o',
    appId: '1:60705047358:ios:d43f89bd9e6423f4b5a26f',
    messagingSenderId: '60705047358',
    projectId: 'pr23-ebf71',
    storageBucket: 'pr23-ebf71.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYzHPbON-icFvsd4WpcoeXAQiRAyPh-rc',
    appId: '1:60705047358:web:440226601f4b3402b5a26f',
    messagingSenderId: '60705047358',
    projectId: 'pr23-ebf71',
    authDomain: 'pr23-ebf71.firebaseapp.com',
    storageBucket: 'pr23-ebf71.firebasestorage.app',
    measurementId: 'G-H15M0NPYBQ',
  );
}
